# -*- coding: utf-8 -*-
"""NEURAL_NETWORK TRAINING -1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gIbqMeJgHMJpnsfqlFX6q6XsQprVzbsd
"""

import sklearn
import pandas as pd
import matplotlib.pyplot as plt
import torch
import numpy
from sklearn.datasets import make_moons

from sklearn.datasets import make_circles
n_samples=1000
a,b =make_moons(n_samples,noise=0.02,random_state=42)
X, y =make_circles(n_samples,noise=0.03,random_state=42)
import pandas as pd
circles=pd.DataFrame({"X1":X[:,0],"X2":X[:,1],
                     "label":y})
circles.head(5)

moons=pd.DataFrame({"A1":a[:,0],"B2":a[:,1],
                     "label":b})
moons.head(5)

plt.scatter(x=a[:, 0], y=a[:, 1], c=b, cmap=plt.cm.RdYlBu)

# PLOTTING DATA
plt.scatter(x=X[:,0],y=X[:,1],c=y,cmap=plt.cm.RdYlBu);

type(X),type(y)
X[:5],y[:5]
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

#METHOD 1 TO CREATE A MODEL
import torch.nn as nn
class CircleModelV0(nn.Module):
  def __init__(self):
    super().__init__()
    self.layer1=nn.Linear(in_features=2,out_features=8)
    self.leayer2=nn.Linear(in_features=8,out_features=1)


  def forward(self,x):
    return self.leayer2(self.layer1(x))
model_0=CircleModelV0()
model_0

#METHOD 2 TO CREATE A MODEL
import torch
import torch.nn as nn

class CircleModelV0(nn.Module):
    def __init__(self):
        super().__init__()
        self.model_1 = nn.Sequential(
            nn.Linear(in_features=2, out_features=8),
            nn.Linear(in_features=8, out_features=1),
        )

    def forward(self, x):
        return self.model_1(x)

# Instantiate and print
model_1 = CircleModelV0()
print(model_1)

model_1.state_dict()